accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'), 
    path('logout/', views.logout_user, name='logout'),  
]

movie/urls.py
from django.urls import path
from movie import views


urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('details/<int:id>/', views.details, name='details'),
    path('add/', views.add_movies, name='add'),
    path('edit/<int:id>/', views.edit_movies, name='edit'),
    path('delete/<int:id>/', views.delete_movies, name='delete'),
    path('addreview/<int:id>/', views.add_review, name='add_review'),
    path('editreview/<int:movie_id>/<int:review_id>/', views.edit_review, name='edit_review'),
    path('deletereview/<int:movie_id>/<int:review_id>/', views.delete_review, name='delete_review'),
]

movie_review/urls.py
from django.contrib import admin
from django.urls import path, include

# Adminpanel 
# username = admin
# password = 1234

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),
    path('accounts/', include('accounts.urls')),
]

movie/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# fiels for movie table
class Movie(models.Model):
    name = models.CharField(max_length=300)
    director = models.CharField(max_length=300)
    cast = models.CharField(max_length=800)
    description = models.TextField(max_length=5000)
    release_date = models.DateField()
    averageRating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000)
    rating = models.FloatField(default=0)


    def __str__(self):
        return self.user.username

movie/forms.py
from django import forms
from .models import *

#movie add form
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name','director','cast','description','release_date','image')


# review
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('comment', 'rating')

movie/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from django.db.models import Avg

# Create your views here.
def home(request):
    query = request.GET.get("title")
    allMovies = None
    
    if query:
        allMovies = Movie.objects.filter(name__icontains=query)
    else:
        allMovies = Movie.objects.all()

    print(allMovies)
    context = {
        'movies' : allMovies
    }
    return render(request, 'index.html', context)

# default page
def details(request, id):
    movie = Movie.objects.get(id=id)
    reviews = Review.objects.filter(movie=id).order_by("-comment")

    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    if average == None:
        average = 0
    average = round(average,2)
    context = {
        'movie':movie,
        'reviews':reviews,
        'average':average
    }
    return render(request, 'details.html', context)


# add movies to the database
def add_movies(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == "POST":
                form = MovieForm(request.POST or None)

                #create if the form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("home")

            else:
                form = MovieForm()
            return render(request, 'addmovies.html', {'form':form, "controller":'Add Movie'})

        # if they are not admin
        else:
            return redirect('home')
    # if they are not logged in
    return redirect('accounts:login')


# Edit the movie
def edit_movies(request,id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the movie linked with id
            movie = Movie.objects.get(id=id)

            # form check
            if request.method == 'POST':
                form = MovieForm(request.POST or None, instance=movie)
                # check if form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect('details', id)
            
            else:
                form = MovieForm(instance=movie)
            return render(request, 'addmovies.html', {'form':form, "controller":'Edit Movie'})

        # if they are not admin
        else:
            return redirect('home')
    # if they are not logged in
    return redirect('accounts:login')


# delete the movie
def delete_movies(request,id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the movies
            movie = Movie.objects.get(id=id)

            #delete the movie
            movie.delete()
            return redirect('home')

        # if they are not admin
        else:
            return redirect('home')
    # if they are not logged in
    return redirect('accounts:login')


# for add review
def add_review(request, id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=id)
        if request.method == 'POST':
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST['comment']
                data.rating = request.POST['rating']
                data.user = request.user
                data.movie = movie
                data.save()
                return redirect('details', id)
        
        else:
            form = ReviewForm()
        return render(request, 'details.html', {'form':form})
    else:
        return redirect('accounts:login')


# for edit review
def edit_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        review = Review.objects.get(movie=movie, id=review_id)


        #check if the review was done by the logged in user
        if request.user == review.user:
            # grant permission
            if request.method == 'POST':
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating >10) or (data.rating <0):
                        error = "Out of range. Please select rating from 0 to 10."
                        return render(request, 'editreview.html', {'error':error, 'form':form})
                    else:
                        data.save()
                        return redirect('details', movie_id)
            
            else:
                form = ReviewForm(instance=review)
            return render(request, 'editreview.html', {'form':form})
        else:
            return redirect('details', movie_id)
    else:
        return redirect('accounts:login')


# delete review
def delete_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)

        #review
        review = Review.objects.get(movie=movie, id=review_id)


        #check if the review was done by the logged in user
        if request.user == review.user:
            # grant permission to delete
            review.delete()
    
        return redirect('details', movie_id)

    else:
        return redirect('accounts:login')

movie/templates/addmovies.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">
                {{ controller }}
            </h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="{{ controller }}" class="btn btn-success">
            </form>
        </div>
    </div>
</div>
{% endblock %}

movie/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>Movie Review</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="http://127.0.0.1:8000/">Movie Review</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="http://127.0.0.1:8000/add/">Add Movies</a>
              </li>


              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ user.username }}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">My Profile</a></li>
                  
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
                </ul>
              </li>

              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              </li>
              {% endif %}


            </ul>
            <form class="d-flex" method="GET" action="{% url 'home' %}">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="title">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    {% block content %}


    {% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

movie/templates/details.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="row">
                    <div class="col-md-4">
                        <img src="{{ movie.image }}" alt="{{ movie.description }}" class="img-fluid">
                    </div>
                    <div class="col-md-8">
                        <h3 class="text-center">
                            {{ movie.name }}
                        </h3>
                        <p>{{ movie.description }}</p>
                        <h5>Director: {{ movie.director }}</h5>
                        <h5>Cast: {{ movie.cast }}</h5>
                        <h5>Rating: {{ average }}/10</h5>

                        {% if request.user.is_authenticated %}
                            {% if request.user.is_superuser %}
                                <a href="{% url 'edit' movie.id %}" class="btn btn-warning">Edit Movie</a>
                                <a href="{% url 'delete' movie.id %}" class="btn btn-danger" onclick="return confirm('Are you sure want to delete this.')">Delete Movie</a>
                            {% endif %}
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div> 
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Add Review</h3>
            <form action="{% url 'add_review' movie.id %}" method="POST">
                {% csrf_token %}
                <label for="comment">Review</label>
                <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>

                <label for="rating">Rating</label>
                <input type="range" id="rangeInput" name="rating" min="0" max="10" step="0.1" value="0" oninput="amount.value.rangeInput.value">

                <output name="amount" id="amount" for="rangeInput">0</output>

                <br>
                <input type="submit" class="btn btn-success" value="Add Review">
            </form>
        </div>
    </div> 

    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            
                {% for review in reviews %} 
                <div class="card" style="background-color: #f5eeee;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                <h5 class="text-left">{{ review.user.username }}</h5>
                                <h5>{{ review.rating }}</h5>

                                {% if request.user == review.user %}
                                    <a href="{% url 'edit_review' movie.id review.id %}">Edit</a>
                                    <a href="{% url 'delete_review' movie.id review.id %}" onclick="return confirm('Are you sure want to delete this.')">Delete</a>
                                {% endif %}

                            </div>
                            <div class="col-md-9">
                                <p>{{ review.comment }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                {% endfor %}
            
        </div>
    </div>
</div>

{% endblock %}

movie/templates/editreview.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Edit Review</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}

                {% if error %}
                    <strong style="color: red;">{{ error }}</strong>
                {% endif %}
                <input type="submit" value="Save Changes" class="btn btn-success">
            </form>
        </div>
    </div>
</div>
{% endblock %}

movie/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <br>
    <div class="card" id="backdrop">
        <div class="card-body">
            <div class="row">
                {% for movie in movies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                                <img src="{{ movie.image }}" alt="" class="img-fluid" width="75%">
                            </div>
                            <h3 class="text-center">
                                {{ movie.name }}
                            </h3>
                            <div class="text-center">
                                <i>{{ movie.release_date }}</i>
                                <a href="details/{{ movie.id }}">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %} 